[package]
name = "d3dcompiler"
version = { workspace = true }
edition = { workspace = true }

[target.'cfg(windows)'.dependencies]
win32 = { workspace = true }
winapi = { workspace = true, features = ["d3dcompiler"] }
