[package]
name = "win32"
version = { workspace = true }
edition = { workspace = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["winbase", "winerror", "unknwnbase"] }
