[package]
name = "project"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
flate2 = { version = "1.0", optional = true }
quickdry = { workspace = true, optional = true }

[features]
read = ["flate2", "quickdry"]
