[package]
name = "loader"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
runner = { workspace = true }
project = { workspace = true, features = ["read"] }
quickdry = { workspace = true }
bstr = { workspace = true }
