[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
gml = { path = "../gml" }
runner = { path = "../runner" }
project = { path = "../project" }
wasm = { path = "../runner/wasm" }
quickdry = "0.1.2"
