name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Rust
      uses: dtolnay/rust-toolchain@nightly
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --locked
    - name: Test
      run: cargo test --locked

  playground:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
    - name: Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: wasm32-unknown-unknown
    - name: Binaryen
      run: |
        curl -s -L https://github.com/WebAssembly/binaryen/releases/download/version_122/binaryen-version_122-x86_64-linux.tar.gz | tar -xzf - -C ~
        echo "$HOME/binaryen-version_122/bin" >> $GITHUB_PATH
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      working-directory: playground
      run: |
        cargo build --locked --release
        wasm-opt -Os -o src/playground.wasm ../target/wasm32-unknown-unknown/release/playground.wasm
        npm ci
        npm run build
    - name: Upload
      if: github.event_name == 'push'
      uses: actions/upload-pages-artifact@v3
      with:
        path: playground/public
    - name: Deploy
      if: github.event_name == 'push'
      uses: actions/deploy-pages@v4
